name: Auto Commit

on:
  schedule:
    - cron: "0 */5 * * *"   # Runs every 5 hours
  workflow_dispatch:        # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "Updated on $(date)" >> README.md

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto commit at $(date)" || echo "No changes to commit"
          git push
